<?php
\kartik\sortable\SortableAsset::register($this);
?>
<script>

$(document).ready(function() {
	// page is generated by ajax based on various things
	// - this is a simple version
  $.get("index.php?r=tbl-contact/get-page", function (content) {
        $("#holder").html(content);
  });



});

</script>

<div id="holder">
</div>
